image: node:carbon

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

test_unit:
  script:
   - npm install
   - npm run test:unit
